included:
  - App
  - Projects
  - Tuist

excluded:
  - .build
  - Tuist/.build
  - Pods
  - Carthage
  - "**/Derived/**"
  - "**/*.generated.swift"

disabled_rules:
  - todo
  - type_body_length
  - function_parameter_count
  - nesting
  - file_length

opt_in_rules:
  - empty_count
  - explicit_init
  - file_name
  - force_cast
  - force_try
  - force_unwrapping
  - vertical_whitespace

control_statement:
  severity: warning

opening_brace:
  severity: warning

statement_position:
  severity: warning

trailing_whitespace:
  severity: warning

file_name:
  severity: warning
  suffix_pattern: "\\+[A-Za-z]+"
  excluded:
    - "SDFonts.swift"
    - "Errors.swift"
    - "TableVersionMigrator.swift"
    - "Dependencies.swift"
    - "Combine+Async.swift"
    - "Project+Templates.swift"

force_cast:
  severity: warning

force_try:
  severity: warning

force_unwrapping:
  severity: warning

vertical_whitespace:
  severity: warning

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60

identifier_name:
  excluded:
    - id
    - x
    - y
    - tx


line_length:
  warning: 120
  error: 300
  ignores_urls: true
  ignores_comments: true

reporter: xcode
